/*Generated by KISSY Module Compiler*/
if(KISSY.Loader){
KISSY.config('modules', {
'biz/page/run': {requires: ['biz/y']},
'biz/y': {requires: ['biz/x']},
'biz/x': {requires: ['overlay', 'switchable']}
});
}
