KISSY.use("toolbar,button,menubutton", function (S, Toolbar) {

        var t = new Toolbar({
            render:"#container",
            children:[
                {
                    content:"menu-button",
                    collapseOnClick:true,
                    xclass:'menu-button',
                    menu:{
                        children:[
                            {
                                content:'item1',
                                xclass:'submenu',
                                menu:{
                                    children:[
                                        {
                                            content:'item1-1'
                                        },
                                        {
                                            content:'item1-2'
                                        }
                                    ]
                                }
                            },
                            {
                                content:'item2'
                            }
                        ]
                    }
                },
                {
                    content:"menu-button3",
                    //collapseOnClick:true,
                    xclass:'menu-button',
                    menu:{
                        children:[
                            {
                                content:'item3',
                                xclass:'submenu',
                                menu:{
                                    children:[
                                        {
                                            content:'item3-1'
                                        },
                                        {
                                            content:'item3-2'
                                        }
                                    ]
                                }
                            },
                            {
                                content:'item4'
                            }
                        ]
                    }
                },
                {
                    content:'button',
                    checkable:true
                },
                {
                    content:"menu-button2",
                    xclass:'menu-button',
                    collapseOnClick:true,
                    menu:{
                        children:[
                            {
                                content:'item2-1'
                            },
                            {
                                content:'item2-2'
                            }
                        ]
                    }
                }
            ]
        }).render();
    });
